language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache
env:
  global:
    - CHECK_PHP_SYNTAX="yes"

sudo: false

install:
  - cp .env.example .env
  - composer self-update
  - travis_retry composer install --dev --no-interaction --prefer-source
  - php artisan key:generate

script:
  - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then php vendor/bin/php-cs-fixer --no-interaction --dry-run --diff -v fix; fi;
  - if [[ "$CHECK_PHP_SYNTAX" == "yes" ]]; then mv ./.php_cs.cache $HOME/.app/cache/.php_cs.cache 2> /dev/null; fi;
  - vendor/bin/phpunit
