language: php

dist: bionic

matrix:
  fast_finish: true
  include:
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.app/cache

services:
  - redis-server
  - mysql

before_install:
  - yes '' | pecl install imagick
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('test') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade --user=root --password=test
  - sudo service mysql restart
  - mysql --user=root --password=test -e 'CREATE DATABASE tracker CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'

install:
  - composer self-update
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-source
  - php artisan storage:link
  - php artisan migrate --env=testing

# Create a storage folder for test coverage report
before_script:
    - mkdir -p build/logs

# Linting and running tests + generating code coverage report
script:
  - php vendor/bin/php-cs-fixer fix --no-interaction --dry-run --diff --using-cache=no -v
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml

after_success:
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)
