language: php

php:
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - setup=stable

matrix:
  allow_failures:
    - php: nightly

sudo: false

install:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script: git reset --hard HEAD

script: vendor/bin/phpunit
