language: php

php:
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

install:
  - cp .env.example .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - php artisan key:generate

script: vendor/bin/phpunit
